import {extractErrorMessage} from '@augment-vir/common';
import {EventHint, Event as SentryEvent} from '@sentry/types';
import {
    EventExtraContextCreator,
    convertEventDetailsToSentryContext,
} from '../event-context/event-context';
import {extractEventSeverity} from '../event-context/event-severity';
import {extractExtraEventContext} from '../event-context/extra-event-context';

/** Attach extra event data for a sentry event. */
export function processSentryEvent(
    /** Event from Sentry. */
    event: SentryEvent,
    /** EventHint generated by Sentry. */
    hint: EventHint,
    /** Optional callback for creating extra event context. */
    createUniversalContext?: EventExtraContextCreator | undefined,
) {
    const extraContext = {
        ...extractExtraEventContext(hint.originalException),
        ...createUniversalContext?.(),
        originalFullMessage: event.message || extractErrorMessage(hint.originalException),
    };
    const sentryContext = convertEventDetailsToSentryContext({
        severity: extractEventSeverity(event),
        extraContext,
    });
    Object.assign(event, sentryContext);

    return event;
}
