import {extractErrorMessage} from '@augment-vir/common';
import type {EventHint} from '@sentry/browser';
import type {ErrorEvent, TransactionEvent} from '@sentry/types';
import {SentryReleaseEnvEnum} from '../env/release-env';
import {getConsoleMethodForSeverity} from '../event-context/event-severity';

/** Creates a handler for Sentry events based on the given env. */
export function createSentryHandler(
    /**
     * The release environment (dev vs prod). Determines whether events should be sent to sentry or
     * not.
     */
    releaseEnv: SentryReleaseEnvEnum,
) {
    /** The actual function that gets called when handling Sentry events. */
    function handleSentrySend(
        /** The event from Sentry. */
        event: TransactionEvent | ErrorEvent,
        /** The EventHint generated by Sentry. */
        hint: EventHint,
    ) {
        const consoleMethod = getConsoleMethodForSeverity(event);

        const message = extractOriginalMessage(event, hint);
        const logArgs = [
            message,
            event.extra,
            {event, hint},
        ];

        if (releaseEnv === SentryReleaseEnvEnum.Dev) {
            consoleMethod('Would have sent to Sentry:', ...logArgs);
            return null;
        } else {
            consoleMethod('Sending to Sentry:', ...logArgs);
            return event;
        }
    }

    return handleSentrySend;
}

/** Tries to extract the original event message from different possible Sentry types. */
export function extractOriginalMessage(
    /** Event from Sentry. */
    event: TransactionEvent | ErrorEvent,
    /** EventHint generated by Sentry. */
    hint: EventHint,
): string {
    const message = event.message || extractErrorMessage(hint.originalException);

    return message;
}
