import {extractErrorMessage} from '@augment-vir/common';
import {
    type ErrorEvent,
    type EventHint,
    type Event as SentryEvent,
    type TransactionEvent,
} from '@sentry/core';
import {
    type EventExtraContextCreator,
    convertEventDetailsToSentryContext,
} from '../event-context/event-context.js';
import {extractEventSeverity} from '../event-context/event-severity.js';
import {
    extractExtraEventContext,
    extractExtraEventTags,
} from '../event-context/extra-event-context.js';

/** Attach extra event data for a sentry event. */
export function processSentryEvent(
    /** Event from Sentry. */
    event: SentryEvent,
    /** EventHint generated by Sentry. */
    hint: EventHint,
    /** Optional callback for creating extra event context. */
    createUniversalContext?: EventExtraContextCreator | undefined,
) {
    const extraContext = {
        ...extractExtraEventContext(hint),
        ...extractExtraEventContext(event),
        ...createUniversalContext?.(),
        originalFullMessage: event.message || extractErrorMessage(hint.originalException),
    };
    const extraTags = {
        ...extractExtraEventTags(hint),
        ...extractExtraEventTags(event),
    };

    const sentryContext = convertEventDetailsToSentryContext(
        {
            severity: extractEventSeverity(event),
            extraContext,
        },
        {
            wasSentPrematurely: false,
        },
    );
    Object.assign(event, sentryContext);

    /**
     * Try to recover one from the hint's original exception. Without this, the event shows as
     * `<unlabeled event>` in Sentry.
     */
    if (!event.message && hint.originalException) {
        event.message = extractErrorMessage(hint.originalException);
    }

    if (Object.keys(extraTags).length) {
        event.tags = {
            ...event.tags,
            ...extraTags,
        };
    }

    return event;
}

/** Tries to extract the original event message from different possible Sentry types. */
export function extractOriginalMessage(
    /** Event from Sentry. */
    event: Pick<TransactionEvent | ErrorEvent, 'message'>,
    /** EventHint generated by Sentry. */
    hint: Readonly<Pick<EventHint, 'originalException'>> | undefined,
): string {
    const message = event.message || extractErrorMessage(hint?.originalException);

    return message;
}
