import {type PartialWithUndefined} from '@augment-vir/common';
import {type EventHint} from '@sentry/browser';
import {type ErrorEvent, type TransactionEvent} from '@sentry/core';
import {extractExtraEventThrottle} from '../event-context/extra-event-context.js';
import {isLoggingDisabled} from '../logging/logging-disabled.js';
import {throttleEventWithLogging} from '../logging/send-log.js';
import {LoggingState, logToConsoleFromSentry} from './log-to-console.js';
import {
    combineThrottleThreshold,
    skipBeforeSendThrottleContextKey,
    type ThrottleOptions,
} from './throttling.js';

/** Creates a handler for Sentry events based on the given env. */
export function createSentryHandler<T extends TransactionEvent | ErrorEvent>({
    isDev,
    isSilent,
    throttleOptions,
}: {
    /** If in dev, events won't be sent to Sentry. They will only be logged in the console. */
    isDev: boolean;
    /** If silent, events won't even get logged to the console. */
    isSilent: boolean;
    throttleOptions: Readonly<PartialWithUndefined<ThrottleOptions>> | undefined;
}) {
    /** The actual function that gets called when handling Sentry events. */
    function handleSentrySend(
        /** The event from Sentry. */
        event: T,
        /** The EventHint generated by Sentry. */
        hint: EventHint,
    ) {
        if (isLoggingDisabled()) {
            return null;
        }

        const wasPreThrottled =
            event.contexts?.[skipBeforeSendThrottleContextKey]?.skipThrottle === true;
        if (event.contexts && skipBeforeSendThrottleContextKey in event.contexts) {
            delete event.contexts[skipBeforeSendThrottleContextKey];
        }

        const eventThrottleOverride = extractExtraEventThrottle(hint);
        if (
            !wasPreThrottled &&
            eventThrottleOverride?.disabled !== true &&
            throttleEventWithLogging(
                event,
                hint,
                combineThrottleThreshold(throttleOptions, eventThrottleOverride?.threshold),
            )
        ) {
            return null;
        }

        if (!event.extra?.wasSentPrematurely) {
            logToConsoleFromSentry({
                event,
                hint,
                loggingState: isDev ? LoggingState.Dev : LoggingState.Prod,
                silent: isSilent,
            });
        }
        return isDev ? null : event;
    }

    return handleSentrySend;
}
