import type {EventHint} from '@sentry/browser';
import type {ErrorEvent, TransactionEvent} from '@sentry/types';
import {LoggingState, logToConsoleFromSentry} from './log-to-console';

/** Creates a handler for Sentry events based on the given env. */
export function createSentryHandler(
    /** If in dev, events won't be sent to Sentry. They will only be logged in the console. */
    isDev: boolean,
) {
    /** The actual function that gets called when handling Sentry events. */
    function handleSentrySend(
        /** The event from Sentry. */
        event: TransactionEvent | ErrorEvent,
        /** The EventHint generated by Sentry. */
        hint: EventHint,
    ) {
        if (!event.extra?.wasSentPrematurely) {
            logToConsoleFromSentry(event, hint, isDev ? LoggingState.Dev : LoggingState.Prod);
        }
        return isDev ? null : event;
    }

    return handleSentrySend;
}
