import {
    getOrSetFromMap,
    mergeDefinedProperties,
    type PartialWithUndefined,
} from '@augment-vir/common';
import {type ErrorEvent, type EventHint, type TransactionEvent} from '@sentry/core';
import {
    calculateRelativeDate,
    getNowInUtcTimezone,
    isDateAfter,
    type AnyDuration,
    type FullDate,
    type UtcTimezone,
} from 'date-vir';
import {FuzzyIndex, type FuzzyIndexKey} from 'fuzzy-vir';
import {sendLog} from '../logging/send-log.js';
import {extractOriginalMessage} from './event-processor.js';

/**
 * Type for entries in {@link throttleCache}.
 *
 * @category Internal
 */
export type ThrottleCacheEntry = {
    intervalCount: number;
    intervalStartAt: FullDate<UtcTimezone>;
};

/**
 * The current throttle cache, keyed by a fuzzy cluster key so near-duplicate error messages share a
 * throttle bucket.
 *
 * @category Internal
 */
export const throttleCache = new Map<FuzzyIndexKey, ThrottleCacheEntry>();

/**
 * Fuzzy index used to group near-duplicate error messages together so they share a single throttle
 * bucket. The `onEvict` hook keeps {@link throttleCache} in sync when a cluster is dropped.
 *
 * @category Internal
 */
export const fuzzyErrorIndex = new FuzzyIndex({
    onEvict(clusterKey) {
        throttleCache.delete(clusterKey);
    },
});

/**
 * Throttling options.
 *
 * @category Internal
 */
export type ThrottleOptions = {
    disableThrottling: boolean;
    /** Duration over which up to `throttleThreshold` events of the same message are allowed. */
    thresholdInterval: AnyDuration;
    /** Disable the sentry log that fires the first time an error is throttled in an interval. */
    disableThrottleLog: boolean;
    /**
     * Within `thresholdInterval`, if an error message is logged more than this many times,
     * additional events are dropped until the interval rolls over.
     */
    throttleThreshold: number;
};

/**
 * Default values for {@link ThrottleOptions}.
 *
 * @category Internal
 */
export const defaultThrottleOptions: ThrottleOptions = {
    disableThrottling: false,
    thresholdInterval: {
        hours: 1,
    },
    disableThrottleLog: false,
    throttleThreshold: 500,
};

/**
 * Determines if an event should be throttled based on previous event counts.
 *
 * @category Internal
 */
export function shouldThrottleEvent(
    /** Event from Sentry. */
    event: Pick<TransactionEvent | ErrorEvent, 'message'>,
    /** EventHint generated by Sentry. */
    hint?: Readonly<Pick<EventHint, 'originalException'>> | undefined,
    userOptions: Readonly<PartialWithUndefined<ThrottleOptions>> = defaultThrottleOptions,
): boolean {
    const options = mergeDefinedProperties(defaultThrottleOptions, userOptions);
    if (options.disableThrottling) {
        return false;
    }
    const errorKey = fuzzyErrorIndex.insert(extractOriginalMessage(event, hint));
    const now = getNowInUtcTimezone();

    const errorThrottleData = getOrSetFromMap(throttleCache, errorKey, () => {
        return {
            intervalCount: 0,
            intervalStartAt: now,
        };
    });

    const intervalNeedsRestart = isDateAfter({
        fullDate: now,
        relativeTo: calculateRelativeDate(
            errorThrottleData.intervalStartAt,
            options.thresholdInterval,
        ),
    });
    if (intervalNeedsRestart) {
        const suppressedCount = errorThrottleData.intervalCount - options.throttleThreshold;
        if (suppressedCount > 0 && !options.disableThrottleLog) {
            sendLog.warning(
                `Throttling ended after suppressing ${suppressedCount} events: ${errorKey}`,
                {
                    context: {
                        suppressedErrorKey: errorKey,
                        suppressedCount,
                    },
                    tags: {
                        suppressedErrorKey: errorKey,
                    },
                },
            );
        }
        errorThrottleData.intervalStartAt = now;
        errorThrottleData.intervalCount = 0;
    }

    errorThrottleData.intervalCount++;

    const shouldThrottle = errorThrottleData.intervalCount > options.throttleThreshold;

    if (
        shouldThrottle &&
        errorThrottleData.intervalCount === options.throttleThreshold + 1 &&
        !options.disableThrottleLog
    ) {
        sendLog.warning(`Throttling started: ${errorKey}`, {
            context: {
                suppressedErrorKey: errorKey,
            },
            tags: {
                suppressedErrorKey: errorKey,
            },
        });
    }

    return shouldThrottle;
}
