import {
    getOrSetFromMap,
    mergeDefinedProperties,
    type PartialWithUndefined,
} from '@augment-vir/common';
import {type ErrorEvent, type EventHint, type TransactionEvent} from '@sentry/core';
import {
    calculateRelativeDate,
    getNowInUtcTimezone,
    isDateAfter,
    type AnyDuration,
    type FullDate,
    type UtcTimezone,
} from 'date-vir';
import {FuzzyIndex, type FuzzyIndexKey} from 'fuzzy-vir';
import {extractOriginalMessage} from './event-processor.js';

/**
 * Type for entries in {@link throttleCache}.
 *
 * @category Internal
 */
export type ThrottleCacheEntry = {
    intervalCount: number;
    intervalStartAt: FullDate<UtcTimezone>;
};

/**
 * The current throttle cache, keyed by a fuzzy cluster key so near-duplicate error messages share a
 * throttle bucket.
 *
 * @category Internal
 */
export const throttleCache = new Map<FuzzyIndexKey, ThrottleCacheEntry>();

/**
 * Fuzzy index used to group near-duplicate error messages together so they share a single throttle
 * bucket. The `onEvict` hook keeps {@link throttleCache} in sync when a cluster is dropped.
 *
 * @category Internal
 */
export const fuzzyErrorIndex = new FuzzyIndex({
    onEvict(clusterKey) {
        throttleCache.delete(clusterKey);
    },
});

/**
 * Throttling options.
 *
 * @category Internal
 */
export type ThrottleOptions = {
    disableThrottling: boolean;
    /** Duration over which up to `throttleThreshold` events of the same message are allowed. */
    thresholdInterval: AnyDuration;
    /** Disable the sentry log that fires the first time an error is throttled in an interval. */
    disableThrottleLog: boolean;
    /**
     * Within `thresholdInterval`, if an error message is logged more than this many times,
     * additional events are dropped until the interval rolls over.
     */
    throttleThreshold: number;
};

/**
 * Default values for {@link ThrottleOptions}.
 *
 * @category Internal
 */
export const defaultThrottleOptions: ThrottleOptions = {
    disableThrottling: false,
    thresholdInterval: {
        hours: 1,
    },
    disableThrottleLog: false,
    throttleThreshold: 500,
};

/**
 * The state transition (if any) that just occurred for an error key. Used by callers to decide
 * whether to emit a `"Throttling started"` or `"Throttling ended after suppressing N events"` log.
 *
 * @category Internal
 */
export type ThrottleTransition =
    | {kind: 'none'}
    | {kind: 'started'}
    | {kind: 'ended'; suppressedCount: number};

/**
 * Result of a single {@link shouldThrottleEvent} call: whether the event should be dropped, the
 * fuzzy cluster key it was bucketed into, and the state transition (if any) that the caller may
 * want to surface as a log.
 *
 * @category Internal
 */
export type ThrottleResult = {
    shouldThrottle: boolean;
    /** Undefined when throttling is disabled (the event isn't bucketed). */
    errorKey: FuzzyIndexKey | undefined;
    transition: ThrottleTransition;
};

/**
 * Determines whether an event should be throttled based on previous event counts.This does not emit
 * any logs itself, the caller is expected to interpret `result.transition` and emit logs as
 * appropriate.
 *
 * @category Internal
 */
export function shouldThrottleEvent(
    /** Event from Sentry. */
    event: Pick<TransactionEvent | ErrorEvent, 'message'>,
    /** EventHint generated by Sentry. */
    hint?: Readonly<Pick<EventHint, 'originalException'>> | undefined,
    userOptions: Readonly<PartialWithUndefined<ThrottleOptions>> = defaultThrottleOptions,
): ThrottleResult {
    const options = mergeDefinedProperties(defaultThrottleOptions, userOptions);
    if (options.disableThrottling) {
        return {
            shouldThrottle: false,
            errorKey: undefined,
            transition: {
                kind: 'none',
            },
        };
    }
    const errorKey = fuzzyErrorIndex.insert(extractOriginalMessage(event, hint));
    const now = getNowInUtcTimezone();

    const errorThrottleData = getOrSetFromMap(throttleCache, errorKey, () => {
        return {
            intervalCount: 0,
            intervalStartAt: now,
        };
    });

    const transitionCandidates: ThrottleTransition[] = [];

    const intervalNeedsRestart = isDateAfter({
        fullDate: now,
        relativeTo: calculateRelativeDate(
            errorThrottleData.intervalStartAt,
            options.thresholdInterval,
        ),
    });
    if (intervalNeedsRestart) {
        const suppressedCount = errorThrottleData.intervalCount - options.throttleThreshold;
        if (suppressedCount > 0) {
            transitionCandidates.push({
                kind: 'ended',
                suppressedCount,
            });
        }
        errorThrottleData.intervalStartAt = now;
        errorThrottleData.intervalCount = 0;
    }

    errorThrottleData.intervalCount++;

    const shouldThrottle = errorThrottleData.intervalCount > options.throttleThreshold;

    if (shouldThrottle && errorThrottleData.intervalCount === options.throttleThreshold + 1) {
        transitionCandidates.push({
            kind: 'started',
        });
    }

    return {
        shouldThrottle,
        errorKey,
        transition: transitionCandidates[0] ?? {
            kind: 'none',
        },
    };
}

/**
 * Reserved key under `event.contexts` that `sendLog` and `handleError` set via `withScope` to tell
 * `handleSentrySend` to skip its own throttle check — they've already done the check synchronously
 * and the event passing through is one they chose to forward. Stripped from the event in
 * `handleSentrySend` so it never reaches Sentry.
 *
 * @category Internal
 */
export const skipBeforeSendThrottleContextKey = '__sentryVirSkipThrottle';

/**
 * The throttle options currently in effect, set by {@link setActiveThrottleOptions} during Sentry
 * initialization. Used by `sendLog` and `handleError` for their synchronous pre-capture throttle
 * checks. `undefined` means Sentry has not yet been initialized.
 *
 * @category Internal
 */
let activeThrottleOptions: Readonly<PartialWithUndefined<ThrottleOptions>> | undefined;

/**
 * Sets the throttle options consulted by `shouldThrottleSync` (in `send-log.ts`). Called by
 * `baseInitSentry`.
 *
 * @category Internal
 */
export function setActiveThrottleOptions(
    options: Readonly<PartialWithUndefined<ThrottleOptions>> | undefined,
): void {
    activeThrottleOptions = options;
}

/**
 * Returns the throttle options registered by the most recent `baseInitSentry` call, or `undefined`
 * if Sentry has not yet been initialized.
 *
 * @category Internal
 */
export function getActiveThrottleOptions():
    | Readonly<PartialWithUndefined<ThrottleOptions>>
    | undefined {
    return activeThrottleOptions;
}

/**
 * Combines a per-call throttle threshold with the active global throttle options, taking the
 * minimum of the two so the per-call threshold can only ever tighten throttling.
 *
 * @category Internal
 */
export function combineThrottleThreshold(
    base: Readonly<PartialWithUndefined<ThrottleOptions>> | undefined,
    perCallThreshold: number | undefined,
): Readonly<PartialWithUndefined<ThrottleOptions>> {
    if (perCallThreshold == undefined) {
        return base ?? {};
    }
    const baseThreshold = base?.throttleThreshold ?? defaultThrottleOptions.throttleThreshold;
    return {
        ...base,
        throttleThreshold: Math.min(baseThreshold, perCallThreshold),
    };
}
