import {
    getOrSetFromMap,
    mergeDefinedProperties,
    type PartialWithUndefined,
} from '@augment-vir/common';
import {type ErrorEvent, type EventHint, type TransactionEvent} from '@sentry/core';
import {
    calculateRelativeDate,
    getNowInUtcTimezone,
    isDateAfter,
    type AnyDuration,
    type FullDate,
    type UtcTimezone,
} from 'date-vir';
import {sendLog} from '../logging/send-log.js';
import {extractOriginalMessage} from './event-processor.js';

/**
 * Type for entries in {@link throttleCache}.
 *
 * @category Internal
 */
export type ThrottleCacheEntry = {
    intervalCount: number;
    intervalStartAt: FullDate<UtcTimezone>;
    throttleStartedAt: FullDate<UtcTimezone> | undefined;
};

/**
 * The current throttle cache.
 *
 * @category Internal
 */
export const throttleCache = new Map<string, ThrottleCacheEntry>();

/**
 * Throttling options.
 *
 * @category Internal
 */
export type ThrottleOptions = {
    disableThrottling: boolean;
    /**
     * When throttling begins, this determines how much time must pass before the error will be
     * logged again.
     */
    thresholdInterval: AnyDuration;
    /**
     * In order for throttling to turn off, the throttle threshold must have not been hit for this
     * entire duration.
     */
    throttleCooldown: AnyDuration;
    /** Enable a sentry log that indicates that an error is being throttled. */
    disableThrottleLog: boolean;
    /** If an error is logged this many times within `logInterval`, it starts getting throttled. */
    throttleThreshold: number;
};

/**
 * Default values for {@link ThrottleOptions}.
 *
 * @category Internal
 */
export const defaultThrottleOptions: ThrottleOptions = {
    disableThrottling: false,
    thresholdInterval: {
        hours: 1,
    },
    disableThrottleLog: false,
    throttleCooldown: {
        days: 1,
    },
    throttleThreshold: 50,
};

/**
 * Determines if an event should be throttled based on previous event counts.
 *
 * @category Internal
 */
export function shouldThrottleEvent(
    /** Event from Sentry. */
    event: Pick<TransactionEvent | ErrorEvent, 'message'>,
    /** EventHint generated by Sentry. */
    hint?: Readonly<Pick<EventHint, 'originalException'>> | undefined,
    userOptions: Readonly<PartialWithUndefined<ThrottleOptions>> = defaultThrottleOptions,
): boolean {
    const options = mergeDefinedProperties(defaultThrottleOptions, userOptions);
    if (options.disableThrottling) {
        return false;
    }
    const errorKey = extractOriginalMessage(event, hint);
    const now = getNowInUtcTimezone();

    const errorThrottleData = getOrSetFromMap(throttleCache, errorKey, () => {
        return {
            intervalCount: 0,
            intervalStartAt: now,
            throttleStartedAt: undefined,
        };
    });
    errorThrottleData.intervalCount++;

    const thresholdSurpassed = errorThrottleData.intervalCount > options.throttleThreshold;
    if (thresholdSurpassed && !errorThrottleData.throttleStartedAt) {
        errorThrottleData.throttleStartedAt = now;
        if (options.disableThrottleLog) {
            sendLog.warning(`Error throttled: ${errorKey}`);
        }
    }

    const intervalNeedsRestart = isDateAfter({
        fullDate: now,
        relativeTo: calculateRelativeDate(
            errorThrottleData.intervalStartAt,
            options.thresholdInterval,
        ),
    });
    if (intervalNeedsRestart) {
        errorThrottleData.intervalStartAt = now;
        if (thresholdSurpassed) {
            /**
             * If an interval surpassed the threshold, always bump the threshold started at up so
             * the cooldown requires all intervals to be below the threshold.
             */
            errorThrottleData.throttleStartedAt = now;
            if (options.disableThrottleLog) {
                sendLog.warning(`Error throttled: ${errorKey}`);
            }
        }
        errorThrottleData.intervalCount = 0;
    }

    if (errorThrottleData.throttleStartedAt) {
        const shouldStopThrottle = isDateAfter({
            fullDate: now,
            relativeTo: calculateRelativeDate(
                errorThrottleData.throttleStartedAt,
                options.throttleCooldown,
            ),
        });

        if (shouldStopThrottle && !thresholdSurpassed) {
            errorThrottleData.throttleStartedAt = undefined;
        }
    }

    return !!errorThrottleData.throttleStartedAt;
}
